spring:
#  liquibase:
#    contexts: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/airbnb_clone
    username: postgres
    password: toor
    driver-class-name: org.postgresql.Driver
    default-schema: airbnb_clone